# GitHub Pages Configuration Variables

# The theme of your site (choose one)
# theme: jekyll-theme-primer
# remote_theme: nikahmadz/prime.dev@v0.1.2-beta
remote_theme: nikahmadz/prime.dev@v0.1.2-beta

# The title of your site
title: Files

# A short description of your site's purpose
# description:
